// Imágenes de productos incluidas en la app (carpeta public/productos).
// Para agregar una nueva: guarda un .webp cuadrado en public/productos y añádelo aquí.
export const IMAGENES_PRODUCTOS: { ruta: string; nombre: string }[] = [
  { ruta: '/productos/agua.webp', nombre: 'Agua' },
  { ruta: '/productos/agua-con-gas.webp', nombre: 'Agua con gas' },
  { ruta: '/productos/botella-aguardiente-amarillo.webp', nombre: 'Botella Aguardiente Amarillo' },
  { ruta: '/productos/bretana.webp', nombre: 'Bretaña' },
  { ruta: '/productos/budweiser.webp', nombre: 'Budweiser' },
  { ruta: '/productos/club-colombia-dorada.webp', nombre: 'Club Colombia Dorada' },
  { ruta: '/productos/coca-cola.webp', nombre: 'Coca-Cola' },
  { ruta: '/productos/corona.webp', nombre: 'Corona' },
  { ruta: '/productos/coronita.webp', nombre: 'Coronita' },
  { ruta: '/productos/costena-bacana.webp', nombre: 'Costeña Bacana' },
  { ruta: '/productos/gatorade.webp', nombre: 'Gatorade' },
  { ruta: '/productos/heineken.webp', nombre: 'Heineken' },
  { ruta: '/productos/lucky-blanco.webp', nombre: 'Lucky Blanco' },
  { ruta: '/productos/marlboro-fusion.webp', nombre: 'Marlboro Fusión' },
  { ruta: '/productos/marlboro-rojo.webp', nombre: 'Marlboro Rojo' },
  { ruta: '/productos/marlboro-sandia.webp', nombre: 'Marlboro Sandía' },
  { ruta: '/productos/media-aguardiente-amarillo.webp', nombre: 'Media Aguardiente Amarillo' },
  { ruta: '/productos/media-antioqueno-azul.webp', nombre: 'Media Antioqueño Azul' },
  { ruta: '/productos/media-nectar-rojo.webp', nombre: 'Media Néctar Rojo' },
  { ruta: '/productos/media-nectar-verde.webp', nombre: 'Media Néctar Verde' },
  { ruta: '/productos/mustang.webp', nombre: 'Mustang' },
  { ruta: '/productos/poker.webp', nombre: 'Poker' },
  { ruta: '/productos/six-pack-poker.webp', nombre: 'Six pack Poker' },
  { ruta: '/productos/six-pack-aguila.webp', nombre: 'Six pack Águila' },
  { ruta: '/productos/todo-rico-bbq.webp', nombre: 'Todo Rico BBQ' },
  { ruta: '/productos/todo-rico-natural.webp', nombre: 'Todo Rico Natural' },
  { ruta: '/productos/aguila.webp', nombre: 'Águila' },
  { ruta: '/productos/aguila-light.webp', nombre: 'Águila Light' },
];
